config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'messages#contact'
  get '/scrap', to: 'messages#scrap'
  get '/parts', to: 'messages#parts'
  get '/breaking', to: 'static_pages#breaking'
    
  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
    include ActiveModel::Model
    attr_accessor :name, :email, :phone, :body, :make, :model, :contact_type
    validates :name, :email, :body, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def contact
        new_message
    end

    def scrap
        new_message
    end

    def parts
        new_message
    end

    def create
        @message = Message.new(message_params)
        
        if @message.valid?
            MessageMailer.contact(@message).deliver_now
            redirect_to root_path
        else
            render :new
        end
            
    end

    private
    
    def new_message
        @message = Message.new
    end

    def message_params
        params.require(:message).permit(:name,:email,:phone,:body, :make, :model, :contact_type)
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def about
    end

    def scrap
    end

    def partrequest
    end

    def breaking
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
    <div class="<%= k %>"> <%= v %> </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="flex-space-between bg-main text-2 ">
  <div id="copyright"class="">
    © GA Motor Spares
    <%= Date.current.year %>
  </div>
  <div id="sitemap" class=" font-2">
    <%= render 'layouts/links'%>
  </div>
  <div id="social" >
    <a id="facebook" class="text-2"target="_blank" href="https://www.facebook.com/ga.motorspares/">
      <%= fa_icon "facebook-square 2x"%>
    </a>
  
  </div>
</footer>

app/views/layouts/_global_site_tag.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108422660-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-108422660-1');
</script>

app/views/layouts/_header.html.erb
<header class="flex-space-around text-1">
    <%= link_to root_path do %>
        <div id="logo-container"class="font-2 ">
            <h1 id="logo" class="text-1"> GA Motor Spares </h1>
            <p id="tagline"class="text-3"> Specialist Ford Breakers </p>
        </div>
        <%end%>
            <div id="opening-container" class=" text-3 text-center">
                <p class="opening "> Mon-Thurs: 8:30am - 5pm</p>
                <p id="opening-2" class="opening"> Fri: 8:30am - 4:30pm, Sat: 9am - 1pm </p>
            </div>
            <div id="contact-container"class="font-3 text-3">
                <h1 id="phone-num"> 01302 771600 </h1>
            </div>
</header>

app/views/layouts/_links.html.erb
<%= link_to 'Home', root_path , class: "text-2"%>
<%= link_to 'About', about_path , class: "text-2"%>
<%= link_to 'Breaking', breaking_path , class: "text-2"%>
<%= link_to 'Scrap', scrap_path , class: "text-2"%>
<%= link_to 'Parts',parts_path , class: "text-2"%>
<%= link_to 'Contact', contact_path, class: "text-2" %>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="flex-space-between bg-main font-2 text-2">
 <%= render 'layouts/links'%>
</div> 

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/global_site_tag" %>
        <title>GA Motor Spares | <%= yield(:title) %></title>
    <%= render "layouts/rails_defaults"%>
    
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Expanded|Montserrat|Open+Sans|Orbitron|Poppins|Raleway" rel="stylesheet">
    <meta name="google-site-verification" content="ieFN0biN5EAVu8id0Ng4eTWIOmzOxFVJEAsjzXv1NnQ" />
  </head>

  <body>
    <div id="page-container" >
        <%= render "layouts/flash" %>
        <%= render "layouts/header" %>
        <%= render "layouts/navbar" %>
        <%= yield %>
        <%= render "layouts/footer"%>
    </div>

    <!--<%= debug(params) if Rails.env.development? %>
  -->
  </body>
</html>

app/views/messages/_form.html.erb
<div id="contact-form" class="flex-1" >
        <%= form_for @message, html: {class: "flex-column"} do |f| %>
            <%= notice %>
            <%= @message.errors.full_messages.join(', ')%>
            <%= f.label :name, "Name"%>
            <%= f.text_field :name, placeholder: 'Enter your name'%>
            <%= f.label :email, "Email Address"%>
            <%= f.email_field :email, placeholder: 'Enter your email address'%>
            <%= f.label :phone, "Phone Number (optional)"%>
            <%= f.text_field :phone, placeholder: 'If you would prefer us to call you enter your phone number'%>
            <% if contact_type == "scrap" || contact_type == "parts"%>
                <%= f.label :make, "Make"%>
                <%= f.text_field :make, placeholder: 'Enter the make of your car'%>
                <%= f.label :model, "Model"%>
                <%= f.text_field :model, placeholder: 'Enter the model of your car'%>
                <%= f.label :body, "Details"%>
                <%= f.text_area :body, placeholder: "Enter any details "%> 
            <% else %>               
                <%= f.label :body, "Your Message"%>
                <%= f.text_area :body, placeholder: "Enter your message here"%>
            <% end %>
            <%= f.hidden_field :contact_type, value: contact_type %>
            <%= f.submit "Send"%>
        <% end%>
    </div>

app/views/messages/contact.html.erb
<% content_for :title, "Contact Us"%>
    <div class="flex-column">
        <div class="text-center">
            <h1> Contact Us </h1>
            <p> Give us a call if you need anything, or use the form to leave us a message. </p>
        </div>
        <div class="flex-space-between">
                <div id="contact-text" class="flex-1 flex-column">
        
                    <h2 class="h2 text-center"> Address </h2>
                    <ul class="text-center">
                        <li> GA Motorspares</li>
                        <li>Unit 2</li>
                        <li>Ash Holt Ind Park</li>
                        <li>Bank End Rd</li>
                        <li>Finningley</li>
                        <li>Doncaster</li>
                        <li>DN9 3NT </li>
                    </ul>
                </div>
                <%=render partial: 'messages/form', locals: {contact_type: "contact"}%>
            </div>
            <div class="flex-center">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2373.596247556444!2d-0.9731374488851355!3d53.493543579912!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48790435d28a9781%3A0x13f7949d353ea3df!2sGA+Motor+Spares!5e0!3m2!1sen!2suk!4v1507740019634"
                            width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
    </div>

 

app/views/messages/parts.html.erb
<% content_for :title, "Part Request"%>
    <div class="flex-column">
        <div class="text-center">
            <h1> Part Request </h1>
            <p> Complete the form or call us if you are looking for a specific part.</p>

        </div>
        <div class="flex-space-between">
            <div id="parts-text" class="flex-1">
            </div>
            <%=render partial: 'messages/form', locals: {contact_type: "parts"}%>
        </div>
    </div>

app/views/messages/scrap.html.erb
<% content_for :title, "Scrap Your Car"%>
<div class="flex-column">
        <div class="text-center">
            <h1> Scrap your car</h1>
            <p> Looking to scrap your car? We are looking for all makes and conditions.
                    
                    Call us or leave a message with the form.</p>

        </div>
        <div class="flex-space-between">
            <div id="scrap-text" class="flex-1">
            </div>
            <%=render partial: 'messages/form', locals: {contact_type: "scrap"}%>
        </div>
    </div>

app/views/static_pages/about.html.erb
<% content_for :title, "About"%>
<div class="flex-column">
        <div class="text-center">
            <h1> About Us</h1>
            <p> </p>
        </div>
        <div class="flex-space-between">
            <div class="flex-1 text-center">
             <p>Based in Doncaster, established in 1989, we have over 25 years experience as a specialist Ford breaker.</p>
            <p> All of our parts are available to collect from our yard, or we can arrange delivery. Use one of the contact options to let us know what you need </p>
            </div>
           
        </div>
    </div>

app/views/static_pages/breaking.html.erb
<% content_for :title, "Breaking"%>
<div class="flex-column">
        <div class="text-center">
            <h1> Currently Breaking</h1>
            <p> Here are the cars that we are currently breaking.</p>

        </div>
        <div class="flex-space-between">
            <div class="flex-1">
            </div>
            <div class="flex-1">
                </div>
        </div>
    </div>

app/views/static_pages/home.html.erb
<% content_for :title, "Specialist Ford Breakers"%>

<div class="flex-column">
    <div id="pitch-text" class="text-center flex-column">
        <h1 id="pitch-title">Welcome to GA Motor Spares.</h1>
        <h2 id="pitch-body"> We are a Doncaster based, Specialist Ford Breakers Yard.</h2>
        <h3> We stock parts for all models of Ford from 1970 to present,
         and will be able to help you find the part you need. We offer a nationwide delivery service, alternatively all of our parts can be collected in person.</h3>
    </div>
    <div id="link-container" class="">
        <%= link_to breaking_path, id: "breaking-box", class:" flex-1 text-2" do%>
            <div class="link-box bg-main">
                <p class="link-header">Currently Breaking</p>
                <p class="link-body">View current breakers.</p>
            </div>
        <% end %>
        <%= link_to parts_path, id: "parts-box",class:"flex-1 text-2" do%>
            <div class="link-box bg-main">
                <p class="link-header">Request a Part </p>
                <p class="link-body"> Need a specific part? </p>
            </div>
        <% end %>
            <%= link_to scrap_path, id: "scrap-box", class:" flex-1 text-2" do%>
                <div class="link-box bg-main">
                    <p class="link-header">Scrap your car </p>
                    <p class="link-body"> Get a quote.</p>
                </div>
            <% end %>
    </div>
</div>